Transform: 'AWS::Serverless-2016-10-31'
Resources:
    filesHandlingFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Runtime: nodejs12.x
            Handler: index.filesHandler
            CodeUri: src
            Events:
                lambdaGetFile:
                    Type: Api
                    Properties:
                        Path: /getFile/{fileName}
                        Method: GET
                lambdaWriteFile:
                    Type: Api
                    Properties:
                        Path: /writeFile
                        Method: POST
                lambdaUpdateFile:
                    Type: Api
                    Properties:
                        Path: /updateFile
                        Method: PUT
                lambdaDeleteFile:
                    Type: Api
                    Properties:
                        Path: /deleteFile/{fileName}
                        Method: DELETE
            Policies:
              -   Version: '2012-10-17'
                  Statement:
                      # Policy needed to use GetObject with right permissions (it needs to list the objects)
                  -   Sid: ListObjectsInBucket
                      Effect: Allow
                      Action: 
                        -   s3:ListBucket
                      Resource:
                        -   arn:aws:s3:::franrobles8-filehandling-bucket
                      # Policy needed to allow all operations in objects with right permissions
                  -   Sid: AllObjectActions
                      Effect: Allow
                      Action: s3:*Object
                      Resource:
                        -   arn:aws:s3:::franrobles8-filehandling-bucket/*
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"