version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app4"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6f83n1n2y4wq"
s3_prefix = "sam-app4"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
