Transform: 'AWS::Serverless-2016-10-31'
Resources:

    # Api created to send a Message to the pdfQueue from an endpoint
    pdfApiCreationFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: nodejs12.x
            Handler: index.pdfSenderHandler
            CodeUri: ./src
            Events:
                lambdaWriteFile:
                    Type: Api
                    Properties:
                        Path: /createPdf
                        Method: POST
            Policies:
              -   SQSSendMessagePolicy:
                      QueueName:
                        !GetAtt PdfSqsQueue.QueueName
    # SQSQueue handler to receive, process messages
    SQSQueueFunction:
        Type: AWS::Serverless::Function
        Properties:
          Handler: index.queueProcessingHandler
          Runtime: nodejs12.x
          CodeUri: ./src
          Policies:
            -   SQSPollerPolicy:
                  QueueName: 
                    !GetAtt PdfSqsQueue.QueueName
            -   S3CrudPolicy:
                  BucketName: xxxxxx-pdf-bucket
    
    # Creation of a default queue
    PdfSqsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "pdfQueue"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
                        